-- V14__Expand_parameter_types.sql

-- Drop the existing param_type enum type
DROP TYPE IF EXISTS param_type CASCADE;

-- Create a new param_type enum with expanded values
CREATE TYPE param_type AS ENUM (
    -- Original parameter types
    'MONTHLY_FEE',
    'OVERDRAFT_LIMIT',
    'INTEREST_RATE',
    
    -- New parameter types
    'ANNUAL_FEE',
    'TRANSACTION_FEE',
    'WITHDRAWAL_FEE',
    'DEPOSIT_FEE',
    'STATEMENT_FEE',
    'MINIMUM_BALANCE_FEE',
    'EARLY_CLOSURE_FEE',
    'DORMANCY_FEE',
    'OVERDRAFT_FEE',
    'INSUFFICIENT_FUNDS_FEE',
    'WIRE_TRANSFER_FEE',
    'INTERNATIONAL_TRANSACTION_FEE',
    'ATM_FEE',
    'CARD_REPLACEMENT_FEE',
    'STOP_PAYMENT_FEE',
    'RETURNED_ITEM_FEE',
    'ACCOUNT_RESEARCH_FEE',
    'PAPER_STATEMENT_FEE',
    'MINIMUM_BALANCE_REQUIREMENT',
    'MAXIMUM_WITHDRAWAL_LIMIT',
    'MAXIMUM_DEPOSIT_LIMIT',
    'DAILY_TRANSACTION_LIMIT',
    'MONTHLY_TRANSACTION_LIMIT',
    'DAILY_WITHDRAWAL_LIMIT',
    'MONTHLY_WITHDRAWAL_LIMIT',
    'DAILY_DEPOSIT_LIMIT',
    'MONTHLY_DEPOSIT_LIMIT',
    'DAILY_TRANSFER_LIMIT',
    'MONTHLY_TRANSFER_LIMIT',
    'MINIMUM_INITIAL_DEPOSIT',
    'MINIMUM_SUBSEQUENT_DEPOSIT',
    'MINIMUM_WITHDRAWAL_AMOUNT',
    'MAXIMUM_BALANCE',
    'BONUS_INTEREST_RATE',
    'PENALTY_INTEREST_RATE',
    'TIERED_INTEREST_RATE_THRESHOLD',
    'INTEREST_RATE_TIER_1',
    'INTEREST_RATE_TIER_2',
    'INTEREST_RATE_TIER_3',
    'INTEREST_RATE_TIER_4',
    'INTEREST_RATE_TIER_5',
    'GRACE_PERIOD_DAYS',
    'NOTICE_PERIOD_DAYS',
    'EARLY_WITHDRAWAL_PENALTY',
    'MINIMUM_AGE_REQUIREMENT',
    'MAXIMUM_AGE_REQUIREMENT',
    'STATEMENT_FREQUENCY_DAYS',
    'INACTIVITY_PERIOD_DAYS',
    'DORMANCY_PERIOD_DAYS'
);

-- Create cast for the new enum type
CREATE CAST (varchar AS param_type) WITH INOUT AS IMPLICIT;
