-- V9__Create_additional_enums.sql
-- Creates additional ENUM types for enhanced account functionality

-- 1) Account sub-type
CREATE TYPE account_subtype_type AS ENUM (
    'STANDARD_CHECKING',
    'INTEREST_CHECKING',
    'REWARDS_CHECKING',
    'FREE_CHECKING',
    'PREMIUM_CHECKING',
    'STANDARD_SAVINGS',
    'HIGH_YIELD_SAVINGS',
    'MONEY_MARKET',
    'CERTIFICATE_OF_DEPOSIT',
    'IRA',
    'FIXED_TERM_DEPOSIT',
    'VARIABLE_TERM_DEPOSIT',
    'PERSONAL_LOAN',
    'AUTO_LOAN',
    'HELOC',
    'STANDARD_CREDIT_CARD',
    'REWARDS_CREDIT_CARD',
    'CASHBACK_CREDIT_CARD',
    'TRAVEL_CREDIT_CARD',
    'BUSINESS_CREDIT_CARD',
    'FIXED_RATE_MORTGAGE',
    'ADJUSTABLE_RATE_MORTGAGE',
    'INTEREST_ONLY_MORTGAGE',
    'STANDARD_BUSINESS_CHECKING',
    'PREMIUM_BUSINESS_CHECKING',
    'STANDARD_BUSINESS_SAVINGS',
    'PREMIUM_BUSINESS_SAVINGS',
    'MULTI_CURRENCY',
    'SINGLE_CURRENCY_FOREIGN',
    'RELATIONSHIP_PREMIUM',
    'WEALTH_MANAGEMENT',
    'YOUTH_SAVINGS',
    'STUDENT_CHECKING',
    'SENIOR_CHECKING',
    'SENIOR_SAVINGS',
    'PENSION_DISTRIBUTION',
    'SOCIAL_SECURITY_BENEFITS',
    'GOVERNMENT_ASSISTANCE'
);

-- 2) Restriction type
CREATE TYPE restriction_type AS ENUM (
    'WITHDRAWAL_HOLD',
    'DEPOSIT_HOLD',
    'ACCOUNT_FREEZE',
    'LEGAL_ORDER',
    'COURT_ORDER',
    'FRAUD_INVESTIGATION',
    'DECEASED_HOLDER',
    'DORMANCY',
    'NEGATIVE_BALANCE',
    'EXCESSIVE_OVERDRAFTS',
    'SUSPICIOUS_ACTIVITY',
    'AML_INVESTIGATION',
    'INTERNATIONAL_TRANSFER_RESTRICTION',
    'HIGH_VALUE_TRANSACTION_RESTRICTION',
    'PENDING_DOCUMENTATION',
    'EXPIRED_IDENTIFICATION',
    'BANKRUPTCY',
    'ESTATE_SETTLEMENT',
    'REGULATORY_COMPLIANCE',
    'SANCTIONS_SCREENING',
    'TRANSACTION_TYPE_RESTRICTION',
    'CHANNEL_RESTRICTION',
    'GEOGRAPHIC_RESTRICTION',
    'CLOSURE_IN_PROGRESS'
);

-- 3) Interest accrual method
CREATE TYPE interest_accrual_method AS ENUM (
    'SIMPLE',
    'DAILY_COMPOUND',
    'MONTHLY_COMPOUND',
    'QUARTERLY_COMPOUND',
    'SEMI_ANNUAL_COMPOUND',
    'ANNUAL_COMPOUND',
    'CONTINUOUS_COMPOUND',
    'DAILY_AVERAGE_BALANCE',
    'MONTHLY_AVERAGE_BALANCE',
    'MINIMUM_BALANCE',
    'TIERED_RATE',
    'STEPPED_RATE',
    'DAY_COUNT_30_360',
    'DAY_COUNT_ACTUAL_360',
    'DAY_COUNT_ACTUAL_365',
    'DAY_COUNT_ACTUAL_ACTUAL'
);

-- 4) Interest payment frequency
CREATE TYPE interest_payment_frequency AS ENUM (
    'DAILY',
    'WEEKLY',
    'BI_WEEKLY',
    'MONTHLY',
    'QUARTERLY',
    'SEMI_ANNUALLY',
    'ANNUALLY',
    'AT_MATURITY',
    'AT_CLOSURE',
    'SPECIFIC_DAY_OF_MONTH',
    'SPECIFIC_DATE',
    'NONE'
);

-- 5) Statement frequency
CREATE TYPE statement_frequency AS ENUM (
    'DAILY',
    'WEEKLY',
    'BI_WEEKLY',
    'MONTHLY',
    'QUARTERLY',
    'SEMI_ANNUALLY',
    'ANNUALLY',
    'ON_DEMAND',
    'NONE'
);

-- 6) Statement delivery method
CREATE TYPE statement_delivery_method AS ENUM (
    'MAIL',
    'EMAIL',
    'ONLINE',
    'MAIL_AND_ONLINE',
    'EMAIL_AND_ONLINE',
    'ALL_METHODS',
    'BRANCH_PICKUP',
    'NONE'
);

-- 7) Notification type
CREATE TYPE notification_type AS ENUM (
    'LOW_BALANCE',
    'LARGE_DEPOSIT',
    'LARGE_WITHDRAWAL',
    'OVERDRAFT',
    'INSUFFICIENT_FUNDS',
    'APPROACHING_MINIMUM_BALANCE',
    'STATEMENT_AVAILABLE',
    'INTEREST_PAYMENT',
    'FEE_CHARGED',
    'STATUS_CHANGE',
    'APPROACHING_MATURITY',
    'MATURITY_REACHED',
    'SUSPICIOUS_ACTIVITY',
    'RESTRICTION_APPLIED',
    'RESTRICTION_REMOVED',
    'APPROACHING_DORMANCY',
    'DORMANCY_APPLIED',
    'GOAL_PROGRESS',
    'GOAL_ACHIEVED',
    'AUTOMATIC_TRANSFER',
    'AUTOMATIC_TRANSFER_FAILED',
    'BALANCE_THRESHOLD',
    'PARAMETER_CHANGE',
    'ACCOUNT_CLOSURE'
);

-- 8) Tax reporting status
CREATE TYPE tax_reporting_status AS ENUM (
    'REPORTABLE',
    'EXEMPT',
    'BACKUP_WITHHOLDING',
    'FATCA_REPORTABLE',
    'CRS_REPORTABLE',
    'FATCA_CRS_REPORTABLE',
    'PENDING_DOCUMENTATION',
    'INCOMPLETE_INFORMATION',
    'NON_REPORTABLE'
);

-- 9) Regulatory status
CREATE TYPE regulatory_status AS ENUM (
    'COMPLIANT',
    'PENDING_DOCUMENTATION',
    'ENHANCED_DUE_DILIGENCE',
    'UNDER_REVIEW',
    'SPECIAL_MONITORING',
    'SANCTIONS_SCREENING',
    'PEP_MONITORING',
    'HIGH_RISK_MONITORING',
    'REGULATORY_EXEMPTION',
    'NON_COMPLIANT',
    'REGULATORY_RESTRICTED'
);

-- Create casts for the new enum types
CREATE CAST (varchar AS account_subtype_type) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS restriction_type) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS interest_accrual_method) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS interest_payment_frequency) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS statement_frequency) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS statement_delivery_method) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS notification_type) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS tax_reporting_status) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS regulatory_status) WITH INOUT AS IMPLICIT;
